spring:
  r2dbc:
    url: r2dbc:pool:postgresql://postgres:postgres@localhost:5433/lista_jogos
    password: postgres
    username: postgres

commons:
  date:
    serializer: yyyy-MM-dd'T'HH:mm:ss
    deserializer: yyyy-MM-dd'T'HH:mm:ssz, yyyy-MM-dd'T'HH:mm:ss.[SSSSSS][SSSSS][SSSS][SSS]'Z', yyyy-MM-dd'T'HH:mm:ss.[SSSSSS][SSSSS][SSSS][SSS], yyyy-MM-dd'T'HH:mm:ss.[SSSSSS][SSSSS][SSSS][SSS]XXX, yyyy-MM-dd'T'HH:mm:ss.S'Z', yyyy-MM-dd'T'HH:mm:ss, yyyy-MM-dd'T'HH:mm:ss.SSSX, yyyy-MM-dd HH:mm:ss, yyyy-MM-dd'T'HH:mm:ss.SSSXXX, yyyy-MM-dd'T'HH:mm:ss.SS'Z'
